/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* A record that carries complete handshake messages and then the start of
   one continued in later records (RFC 8446 5.1, RFC 5246 6.2.1).  The state
   machine that arms reassembly must keep only the continued message's bytes
   at the start of the record buffer, so reassembly neither overruns nor
   re-reads the messages in front of it.

   K legs drive _nx_secure_tls_process_record with the real TLS 1.3 client
   state machine and the real EncryptedExtensions processor.  S legs call the
   real server state machines the way _nx_secure_tls_process_record does (the
   record already copied into the session buffer).  G legs call a server state
   machine directly with a buffer that is not the session buffer, or with no
   session buffer, as the existing coverage tests do, and require that nothing
   changes.

   Replaced by definitions in this executable (the library's own calls reach
   them through its PLT; any other session goes to the real function):
   _nx_secure_tls_record_payload_decrypt returns the record payload without a
   16-byte tag (TLS 1.3 framing, not authentic decryption);
   _nx_secure_tls_process_remote_certificate keeps the body it is given;
   _nx_secure_tls_1_3_transcript_hash_save and
   _nx_secure_tls_handshake_hash_update count their calls and lengths.
   So the S legs prove the compaction and its guard in the server state
   machines, not an authentic server handshake.  Every input is well formed. */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include   <dlfcn.h>
#include   <string.h>
#include   "tx_api.h"
#include   "nx_api.h"
#include   "nx_secure_tls_api.h"
#include   "nx_secure_tls.h"

extern VOID    test_control_return(UINT status);
extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

#if defined(__linux__) && \
    (!defined(NX_SECURE_TLS_CLIENT_DISABLED) || !defined(NX_SECURE_TLS_SERVER_DISABLED))

#define METADATA_SIZE       16000
#define LEG_PACKETS         8
#define PACKET_SIZE         1536
#define POOL_AREA           ((LEG_PACKETS * (PACKET_SIZE + sizeof(NX_PACKET))) / sizeof(ULONG))
#define AEAD_TAG            16
#define MAX_LEGS            8
#define MAX_HASHES          8

/* Messages.  C is a 96-byte Certificate (4-byte header + 92); EE an empty
   EncryptedExtensions; the server legs use a 12-byte client Certificate
   (4 + 8) followed by the first 24 bytes of a 68-byte message (4 + 64). */
#define C_LENGTH            96
#define EE_LENGTH           6
#define SERVER_CERT_LENGTH  12
#define NEXT_LENGTH         68
#define NEXT_PART           24

static UCHAR                   message_c[C_LENGTH];
static const UCHAR             message_ee[EE_LENGTH] = { NX_SECURE_TLS_ENCRYPTED_EXTENSIONS, 0, 0, 2, 0, 0 };
static UCHAR                   server_cert[SERVER_CERT_LENGTH];
static UCHAR                   next_message[NEXT_LENGTH];

static NX_SECURE_TLS_SESSION   csession;
static NX_SECURE_TLS_SESSION   ssession;
static UCHAR                   cmetadata[METADATA_SIZE];
static UCHAR                   smetadata[METADATA_SIZE];
static UCHAR                   cbuffer[4000];
static UCHAR                   sbuffer[4000];
static NX_PACKET_POOL          leg_pool[MAX_LEGS];
static ULONG                   leg_pool_area[MAX_LEGS][POOL_AREA];
static UINT                    legs_run;
static UINT                    failures;
static UCHAR                   scratch[600];

/* What the replaced functions saw. */
static UINT                    decrypt_calls;
static UINT                    cert_calls;
static UINT                    cert_length;
static UCHAR                   cert_body[C_LENGTH];
static UINT                    save_calls;
static UINT                    hash_calls;
static UINT                    hash_length[MAX_HASHES];

static UINT ours(NX_SECURE_TLS_SESSION *tls_session)
{
    return((tls_session == &csession) || (tls_session == &ssession));
}

/* -----===== the replaced functions =====----- */

typedef UINT (*DECRYPT_FN)(NX_SECURE_TLS_SESSION *, NX_PACKET *, UINT, UINT, NX_PACKET **, ULONG *, UCHAR, UINT);
typedef UINT (*CERT_FN)(NX_SECURE_TLS_SESSION *, UCHAR *, UINT, UINT);
typedef UINT (*SAVE_FN)(NX_SECURE_TLS_SESSION *, UINT, UINT);
typedef UINT (*HASH_FN)(NX_SECURE_TLS_SESSION *, UCHAR *, UINT);

UINT _nx_secure_tls_record_payload_decrypt(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *encrypted_packet,
                                           UINT offset, UINT message_length, NX_PACKET **decrypted_packet,
                                           ULONG sequence_num[NX_SECURE_TLS_SEQUENCE_NUMBER_SIZE],
                                           UCHAR record_type, UINT wait_option)
{
static DECRYPT_FN real_fn;
NX_PACKET *packet;
ULONG      copied;
UINT       status;

    if (!ours(tls_session))
    {
        if (real_fn == NX_NULL)
        {
            real_fn = (DECRYPT_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_record_payload_decrypt");
        }
        return(real_fn(tls_session, encrypted_packet, offset, message_length, decrypted_packet,
                       sequence_num, record_type, wait_option));
    }
    decrypt_calls++;
    if ((message_length <= AEAD_TAG) || (message_length - AEAD_TAG > sizeof(scratch)) ||
        nx_packet_data_extract_offset(encrypted_packet, offset, scratch, message_length - AEAD_TAG, &copied) ||
        (copied != message_length - AEAD_TAG))
    {
        return(NX_SECURE_TLS_INVALID_PACKET);
    }
    status = nx_packet_allocate(tls_session -> nx_secure_tls_packet_pool, &packet, NX_IPv4_TCP_PACKET, NX_NO_WAIT);
    if (status)
    {
        return(status);
    }
    status = nx_packet_data_append(packet, scratch, copied, tls_session -> nx_secure_tls_packet_pool, NX_NO_WAIT);
    if (status)
    {
        nx_packet_release(packet);
        return(status);
    }
    *decrypted_packet = packet;
    return(NX_SECURE_TLS_SUCCESS);
}

UINT _nx_secure_tls_process_remote_certificate(NX_SECURE_TLS_SESSION *tls_session, UCHAR *packet_buffer,
                                               UINT message_length, UINT data_length)
{
static CERT_FN real_fn;

    if (!ours(tls_session))
    {
        if (real_fn == NX_NULL)
        {
            real_fn = (CERT_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_process_remote_certificate");
        }
        return(real_fn(tls_session, packet_buffer, message_length, data_length));
    }
    cert_calls++;
    cert_length = message_length;
    memcpy(cert_body, packet_buffer, (message_length < sizeof(cert_body)) ? message_length : sizeof(cert_body));
#ifndef NX_SECURE_TLS_CLIENT_DISABLED
    if (tls_session == &csession)
    {
        /* As the real processor does at its end. */
        tls_session -> nx_secure_tls_client_state = NX_SECURE_TLS_CLIENT_STATE_SERVER_CERTIFICATE;
    }
#endif
    return(NX_SUCCESS);
}

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
UINT _nx_secure_tls_1_3_transcript_hash_save(NX_SECURE_TLS_SESSION *tls_session, UINT hash_index, UINT need_copy)
{
static SAVE_FN real_fn;

    if (!ours(tls_session))
    {
        if (real_fn == NX_NULL)
        {
            real_fn = (SAVE_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_1_3_transcript_hash_save");
        }
        return(real_fn(tls_session, hash_index, need_copy));
    }
    save_calls++;
    return(NX_SUCCESS);
}
#endif

UINT _nx_secure_tls_handshake_hash_update(NX_SECURE_TLS_SESSION *tls_session, UCHAR *data, UINT length)
{
static HASH_FN real_fn;

    if (!ours(tls_session))
    {
        if (real_fn == NX_NULL)
        {
            real_fn = (HASH_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_handshake_hash_update");
        }
        return(real_fn(tls_session, data, length));
    }
    if (hash_calls < MAX_HASHES)
    {
        hash_length[hash_calls] = length;
    }
    hash_calls++;
    return(NX_SUCCESS);
}

/* -----===== checks =====----- */

static UINT leg_ok;

#define CHECK(cond, ...) do { if (!(cond)) { printf("    FAIL: " __VA_ARGS__); printf("\n"); leg_ok = NX_FALSE; } } while (0)

static VOID counters_reset(VOID)
{
    decrypt_calls = 0;
    cert_calls = 0;
    cert_length = 0;
    memset(cert_body, 0, sizeof(cert_body));
    save_calls = 0;
    hash_calls = 0;
    memset(hash_length, 0, sizeof(hash_length));
}

static VOID hashes_check(UINT count, UINT first, UINT second)
{
    CHECK(hash_calls == count, "hash calls %u, expected %u", hash_calls, count);
    if (count > 0)
    {
        CHECK(hash_length[0] == first, "hash 1 length %u, expected %u", hash_length[0], first);
    }
    if (count > 1)
    {
        CHECK(hash_length[1] == second, "hash 2 length %u, expected %u", hash_length[1], second);
    }
}

static VOID leg_end(const CHAR *name, NX_PACKET_POOL *pool, ULONG available, ULONG invalid)
{
    if (pool != NX_NULL)
    {
        printf("    pool %lu/%lu invalid_releases %lu\n", pool -> nx_packet_pool_available, available,
               pool -> nx_packet_pool_invalid_releases - invalid);
        CHECK(pool -> nx_packet_pool_available == available, "pool not whole");
        CHECK(pool -> nx_packet_pool_invalid_releases == invalid, "invalid release");
    }
    printf("  %-48s %s\n", name, leg_ok ? "PASS" : "FAIL");
    legs_run++;
    if (!leg_ok)
    {
        failures++;
    }
}

/* -----===== K legs: process_record with the real TLS 1.3 client =====----- */

#if (NX_SECURE_TLS_TLS_1_3_ENABLED) && !defined(NX_SECURE_TLS_CLIENT_DISABLED)

typedef struct
{
    UINT            status;             /* expected status of this call */
    ULONG           bytes;              /* bytes_processed returned (and saved on NX_CONTINUE) */
    ULONG           copied;             /* packet_buffer_bytes_copied after the call */
    ULONG           expected;           /* handshake_record_expected_length after the call */
    UINT            fragment;           /* fragment state after the call */
    UINT            client_state;
    UINT            certs;              /* certificate processor calls so far */
    UINT            hashes;             /* hash calls so far, and the first two lengths */
    UINT            hash1;
    UINT            hash2;
    UINT            sequence;
    UINT            dead_from;          /* KEY_CLEAR: buffer[dead_from..dead_to) must be zero */
    UINT            dead_to;
} K_CALL;

typedef struct
{
    const CHAR *name;
    UINT        prefix_ee;              /* the first record starts with EE */
    UINT        cuts[3];                /* C split points (0 ends): record i carries C[cut i-1 .. cut i) */
    UINT        records;
    K_CALL      call[3];
} K_LEG;

#define ST_SH   NX_SECURE_TLS_CLIENT_STATE_SERVERHELLO
#define ST_EE   NX_SECURE_TLS_CLIENT_STATE_ENCRYPTED_EXTENSIONS
#define ST_CERT NX_SECURE_TLS_CLIENT_STATE_SERVER_CERTIFICATE
#define RX      NX_SECURE_TLS_HANDSHAKE_RECEIVED_FRAGMENT
#define NF      NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT

/* Wire lengths: record = 5 + plaintext + 1 inner type + 16 tag.
   K1/K2 record 1: 6 + 40 = 46 -> 68; K1 record 2: 56 -> 78;
   K2 records 2, 3: 50 -> 72, 6 -> 28; K5: 60 -> 82, 36 -> 58. */
static const K_LEG k_legs[] =
{
    { "K1 EE + Certificate start, rest",          1, { 40, 96, 0 }, 2,
      { { NX_CONTINUE, 68,  40, 96, RX, ST_EE,   0, 1, 6, 0,  1, 40, 46 },
        { NX_SUCCESS,  146, 96, 0,  NF, ST_CERT, 1, 2, 6, 96, 2, 0,  0 } } },
    { "K2 EE + Certificate start, middle, end",   1, { 40, 90, 96 }, 3,
      { { NX_CONTINUE, 68,  40, 96, RX, ST_EE,   0, 1, 6, 0,  1, 40, 46 },
        { NX_CONTINUE, 140, 90, 96, RX, ST_EE,   0, 1, 6, 0,  2, 0,  0 },
        { NX_SUCCESS,  168, 96, 0,  NF, ST_CERT, 1, 2, 6, 96, 3, 0,  0 } } },
    { "K5 Certificate in two pure fragments",     0, { 60, 96, 0 }, 2,
      { { NX_CONTINUE, 82,  60, 96, RX, ST_SH,   0, 0, 0, 0,  1, 0,  0 },
        { NX_SUCCESS,  140, 96, 0,  NF, ST_CERT, 1, 1, 96, 0, 2, 0,  0 } } },
};

static UINT k_record(UCHAR *out, const UCHAR *plain, UINT length)
{
UINT wire = length + 1 + AEAD_TAG;

    out[0] = NX_SECURE_TLS_APPLICATION_DATA;
    out[1] = 0x03;
    out[2] = 0x03;
    out[3] = (UCHAR)(wire >> 8);
    out[4] = (UCHAR)wire;
    memcpy(&out[5], plain, length);
    out[5 + length] = NX_SECURE_TLS_HANDSHAKE;
    memset(&out[6 + length], 0, AEAD_TAG);
    return(5 + wire);
}

static VOID k_leg_run(const K_LEG *leg)
{
NX_PACKET_POOL *pool = &leg_pool[legs_run];
NX_PACKET      *packet;
UCHAR           plain[200];
UCHAR           record[260];
UINT            plain_length;
UINT            record_length;
UINT            from = 0;
UINT            i;
UINT            k;
UINT            status;
ULONG           bytes_processed;
ULONG           available;
ULONG           invalid;
const K_CALL   *e;

    leg_ok = NX_TRUE;
    printf("  %s\n", leg -> name);
    if (nx_packet_pool_create(pool, "leg pool", PACKET_SIZE, leg_pool_area[legs_run], sizeof(leg_pool_area[legs_run])))
    {
        CHECK(0, "pool create");
        leg_end(leg -> name, NX_NULL, 0, 0);
        return;
    }
    available = pool -> nx_packet_pool_available;
    invalid = pool -> nx_packet_pool_invalid_releases;

    csession.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_CLIENT;
    csession.nx_secure_tls_client_state = NX_SECURE_TLS_CLIENT_STATE_SERVERHELLO;
    csession.nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_2;
    csession.nx_secure_tls_1_3 = NX_TRUE;
    csession.nx_secure_tls_local_session_active = NX_TRUE;
    csession.nx_secure_tls_remote_session_active = NX_TRUE;
    csession.nx_secure_tls_packet_pool = pool;
    csession.nx_secure_tls_packet_buffer = cbuffer;
    csession.nx_secure_tls_packet_buffer_size = sizeof(cbuffer);
    csession.nx_secure_record_queue_header = NX_NULL;
    csession.nx_secure_record_decrypted_packet = NX_NULL;
    csession.nx_secure_tls_record_offset = 0;
    csession.nx_secure_tls_bytes_processed = 0;
    csession.nx_secure_tls_packet_buffer_bytes_copied = 0;
    csession.nx_secure_tls_handshake_record_expected_length = 0;
    csession.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;
    csession.nx_secure_tls_remote_sequence_number[0] = 0;
    csession.nx_secure_tls_remote_sequence_number[1] = 0;
    memset(cbuffer, 0, sizeof(cbuffer));
    counters_reset();

    for (i = 0; i < leg -> records; i++)
    {
        e = &leg -> call[i];

        /* Record i: [EE] + C[from .. cut i). */
        plain_length = 0;
        if ((i == 0) && leg -> prefix_ee)
        {
            memcpy(plain, message_ee, EE_LENGTH);
            plain_length = EE_LENGTH;
        }
        memcpy(&plain[plain_length], &message_c[from], leg -> cuts[i] - from);
        plain_length += leg -> cuts[i] - from;
        from = leg -> cuts[i];
        record_length = k_record(record, plain, plain_length);

        status = nx_packet_allocate(pool, &packet, NX_IPv4_TCP_PACKET, NX_NO_WAIT);
        if (status == NX_SUCCESS)
        {
            status = nx_packet_data_append(packet, record, record_length, pool, NX_NO_WAIT);
        }
        if (status)
        {
            CHECK(0, "record %u packet 0x%x", i + 1, status);
            break;
        }

        bytes_processed = 0xDEADBEEF;
        status = _nx_secure_tls_process_record(&csession, packet, &bytes_processed, NX_NO_WAIT);
        printf("    record %u (%u B plaintext): status 0x%x bytes_processed %lu saved %lu/%lu copied %lu expected %lu"
               " fragment %u client_state %u cert %u hash %u [%u %u] sequence %lu/%lu\n",
               i + 1, plain_length, status, bytes_processed, csession.nx_secure_tls_record_offset,
               csession.nx_secure_tls_bytes_processed, csession.nx_secure_tls_packet_buffer_bytes_copied,
               csession.nx_secure_tls_handshake_record_expected_length,
               (UINT)csession.nx_secure_tls_handshake_record_fragment_state,
               (UINT)csession.nx_secure_tls_client_state, cert_calls, hash_calls, hash_length[0], hash_length[1],
               csession.nx_secure_tls_remote_sequence_number[1], csession.nx_secure_tls_remote_sequence_number[0]);

        CHECK(status == e -> status, "status 0x%x, expected 0x%x", status, e -> status);
        CHECK(bytes_processed == e -> bytes, "bytes_processed %lu, expected %lu", bytes_processed, e -> bytes);
        if (e -> status == NX_CONTINUE)
        {
            CHECK((csession.nx_secure_tls_record_offset == e -> bytes) &&
                  (csession.nx_secure_tls_bytes_processed == e -> bytes),
                  "saved %lu/%lu, expected %lu", csession.nx_secure_tls_record_offset,
                  csession.nx_secure_tls_bytes_processed, e -> bytes);
        }
        else
        {
            CHECK(csession.nx_secure_tls_record_offset == 0, "saved offset %lu, expected 0",
                  csession.nx_secure_tls_record_offset);
        }
        CHECK(csession.nx_secure_tls_packet_buffer_bytes_copied == e -> copied, "copied %lu, expected %lu",
              csession.nx_secure_tls_packet_buffer_bytes_copied, e -> copied);
        CHECK(csession.nx_secure_tls_handshake_record_expected_length == e -> expected, "expected length %lu, expected %lu",
              csession.nx_secure_tls_handshake_record_expected_length, e -> expected);
        CHECK(csession.nx_secure_tls_handshake_record_fragment_state == e -> fragment, "fragment state %u, expected %u",
              (UINT)csession.nx_secure_tls_handshake_record_fragment_state, e -> fragment);
        CHECK(csession.nx_secure_tls_client_state == e -> client_state, "client state %u, expected %u",
              (UINT)csession.nx_secure_tls_client_state, e -> client_state);
        CHECK(cert_calls == e -> certs, "certificate calls %u, expected %u", cert_calls, e -> certs);
        hashes_check(e -> hashes, e -> hash1, e -> hash2);
        CHECK((csession.nx_secure_tls_remote_sequence_number[0] == e -> sequence) &&
              (csession.nx_secure_tls_remote_sequence_number[1] == 0),
              "sequence %lu/%lu, expected 0/%u", csession.nx_secure_tls_remote_sequence_number[1],
              csession.nx_secure_tls_remote_sequence_number[0], e -> sequence);
        CHECK(decrypt_calls == i + 1, "decrypt calls %u, expected %u", decrypt_calls, i + 1);
        if (e -> status == NX_CONTINUE)
        {

            /* The buffer starts with C and holds exactly C's bytes received so far. */
            CHECK(memcmp(cbuffer, message_c, e -> copied) == 0, "buffer is not C[0..%lu)", e -> copied);
        }
#ifdef NX_SECURE_KEY_CLEAR
        for (k = e -> dead_from; k < e -> dead_to; k++)
        {
            CHECK(cbuffer[k] == 0, "KEY_CLEAR: buffer[%u] = 0x%02x after compaction", k, cbuffer[k]);
        }
#else
        NX_PARAMETER_NOT_USED(k);
#endif
        if (status != NX_CONTINUE)
        {
            break;
        }
    }

    if (leg_ok)
    {
        CHECK(cert_length == C_LENGTH - 4, "certificate body length %u, expected %u", cert_length, C_LENGTH - 4);
        CHECK(memcmp(cert_body, &message_c[4], C_LENGTH - 4) == 0, "certificate body differs from C");
    }

    if (csession.nx_secure_record_decrypted_packet)
    {
        nx_packet_release(csession.nx_secure_record_decrypted_packet);
        csession.nx_secure_record_decrypted_packet = NX_NULL;
    }
    if (csession.nx_secure_record_queue_header)
    {
        nx_packet_release(csession.nx_secure_record_queue_header);
        csession.nx_secure_record_queue_header = NX_NULL;
    }
    csession.nx_secure_tls_record_offset = 0;
    csession.nx_secure_tls_bytes_processed = 0;
    csession.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;
    leg_end(leg -> name, pool, available, invalid);
}
#endif

/* -----===== S and G legs: the server state machines, called directly =====----- */

#if !defined(NX_SECURE_TLS_SERVER_DISABLED) && defined(NX_SECURE_ENABLE_CLIENT_CERTIFICATE_VERIFY)

typedef UINT (*SERVER_MACHINE)(NX_SECURE_TLS_SESSION *, UCHAR *, UINT, ULONG);

#define SERVER_INPUT (SERVER_CERT_LENGTH + NEXT_PART)

/* where: 0 = the session buffer (the process_record contract), 1 = a local
   array, 2 = a local array with no session buffer. */
static VOID s_leg_run(const CHAR *name, SERVER_MACHINE machine, UCHAR next_type, UINT where, UINT saves)
{
UCHAR  input[SERVER_INPUT];
UCHAR  local[SERVER_INPUT];
UCHAR *buffer;
UINT   status;
UINT   k;
UINT   compact = (where == 0);

    leg_ok = NX_TRUE;
    printf("  %s\n", name);

    memcpy(input, server_cert, SERVER_CERT_LENGTH);
    next_message[0] = next_type;
    memcpy(&input[SERVER_CERT_LENGTH], next_message, NEXT_PART);

    ssession.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_SERVER;
    ssession.nx_secure_tls_server_state = NX_SECURE_TLS_SERVER_STATE_IDLE;
    ssession.nx_secure_tls_packet_buffer = (where == 2) ? NX_NULL : sbuffer;
    ssession.nx_secure_tls_packet_buffer_size = sizeof(sbuffer);
    ssession.nx_secure_tls_packet_buffer_bytes_copied = SERVER_INPUT;
    ssession.nx_secure_tls_handshake_record_expected_length = 0;
    ssession.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;
    memset(sbuffer, 0xEE, sizeof(sbuffer));
    if (where == 0)
    {
        memcpy(sbuffer, input, SERVER_INPUT);
        buffer = sbuffer;
    }
    else
    {
        memcpy(local, input, SERVER_INPUT);
        buffer = local;
    }
    counters_reset();

    status = machine(&ssession, buffer, SERVER_INPUT, NX_NO_WAIT);
    printf("    status 0x%x copied %lu expected %lu fragment %u server_state %u cert %u (%u B) hash %u [%u] save %u\n",
           status, ssession.nx_secure_tls_packet_buffer_bytes_copied,
           ssession.nx_secure_tls_handshake_record_expected_length,
           (UINT)ssession.nx_secure_tls_handshake_record_fragment_state, (UINT)ssession.nx_secure_tls_server_state,
           cert_calls, cert_length, hash_calls, hash_length[0], save_calls);

    CHECK(status == NX_SECURE_TLS_HANDSHAKE_FRAGMENT_RECEIVED, "status 0x%x, expected 0x%x", status,
          NX_SECURE_TLS_HANDSHAKE_FRAGMENT_RECEIVED);
    CHECK(ssession.nx_secure_tls_handshake_record_expected_length == NEXT_LENGTH, "expected length %lu, expected %u",
          ssession.nx_secure_tls_handshake_record_expected_length, NEXT_LENGTH);
    CHECK(ssession.nx_secure_tls_handshake_record_fragment_state == NX_SECURE_TLS_HANDSHAKE_RECEIVED_FRAGMENT,
          "fragment state %u", (UINT)ssession.nx_secure_tls_handshake_record_fragment_state);
    CHECK(ssession.nx_secure_tls_server_state == NX_SECURE_TLS_SERVER_STATE_CLIENT_CERTIFICATE,
          "server state %u, expected %u", (UINT)ssession.nx_secure_tls_server_state,
          NX_SECURE_TLS_SERVER_STATE_CLIENT_CERTIFICATE);
    CHECK((cert_calls == 1) && (cert_length == SERVER_CERT_LENGTH - 4) &&
          (memcmp(cert_body, &server_cert[4], SERVER_CERT_LENGTH - 4) == 0),
          "certificate processor calls %u length %u", cert_calls, cert_length);
    hashes_check(1, SERVER_CERT_LENGTH, 0);
    CHECK(save_calls == saves, "transcript saves %u, expected %u", save_calls, saves);

    if (compact)
    {
        CHECK(ssession.nx_secure_tls_packet_buffer_bytes_copied == NEXT_PART, "copied %lu, expected %u",
              ssession.nx_secure_tls_packet_buffer_bytes_copied, NEXT_PART);
        CHECK(memcmp(sbuffer, next_message, NEXT_PART) == 0, "buffer does not start with the fragment");
#ifdef NX_SECURE_KEY_CLEAR
        for (k = NEXT_PART; k < SERVER_INPUT; k++)
        {
            CHECK(sbuffer[k] == 0, "KEY_CLEAR: buffer[%u] = 0x%02x after compaction", k, sbuffer[k]);
        }
#endif
    }
    else
    {

        /* Not the process_record contract: nothing may move or change. */
        CHECK(ssession.nx_secure_tls_packet_buffer_bytes_copied == SERVER_INPUT, "copied %lu, expected unchanged %u",
              ssession.nx_secure_tls_packet_buffer_bytes_copied, SERVER_INPUT);
        CHECK(memcmp(local, input, SERVER_INPUT) == 0, "caller's buffer changed");
        for (k = 0; k < SERVER_INPUT; k++)
        {
            if (sbuffer[k] != 0xEE)
            {
                CHECK(0, "session buffer changed at %u", k);
                break;
            }
        }
    }
    NX_PARAMETER_NOT_USED(k);

    ssession.nx_secure_tls_packet_buffer = sbuffer;
    ssession.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;
    ssession.nx_secure_tls_handshake_record_expected_length = 0;
    leg_end(name, NX_NULL, 0, 0);
}
#endif

/* -----===== the test =====----- */

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_process_record_coalesced_test_application_define(void *first_unused_memory)
#endif
{
UINT i;
UINT status;

    NX_PARAMETER_NOT_USED(first_unused_memory);
    NX_PARAMETER_NOT_USED(i);
    NX_PARAMETER_NOT_USED(status);

    printf("NetX Secure Test:   TLS Process Record Coalesced Test..................\n");

    /* Message bytes: non-zero bodies, so a KEY_CLEAR zero is never a coincidence. */
    message_c[0] = NX_SECURE_TLS_CERTIFICATE_MSG;
    message_c[3] = C_LENGTH - 4;
    for (i = 4; i < C_LENGTH; i++)
    {
        message_c[i] = (UCHAR)(0x40 + (i % 61));
    }
    server_cert[0] = NX_SECURE_TLS_CERTIFICATE_MSG;
    server_cert[3] = SERVER_CERT_LENGTH - 4;
    for (i = 4; i < SERVER_CERT_LENGTH; i++)
    {
        server_cert[i] = (UCHAR)(0xA0 + i);
    }
    next_message[3] = NEXT_LENGTH - 4;
    for (i = 4; i < NEXT_LENGTH; i++)
    {
        next_message[i] = (UCHAR)(0x11 + i);
    }

#if (NX_SECURE_TLS_TLS_1_3_ENABLED) && !defined(NX_SECURE_TLS_CLIENT_DISABLED)
    status = nx_secure_tls_session_create(&csession, &nx_crypto_tls_ciphers, cmetadata, sizeof(cmetadata));
    if (status)
    {
        printf("  client session create 0x%x\nERROR!\n", status);
        test_control_return(1);
        return;
    }
    for (i = 0; i < sizeof(k_legs) / sizeof(k_legs[0]); i++)
    {
        k_leg_run(&k_legs[i]);
    }
#else
    NX_PARAMETER_NOT_USED(cmetadata);
    NX_PARAMETER_NOT_USED(cbuffer);
    printf("  K1, K2, K5: N/A, TLS 1.3 client is not compiled in\n");
#endif

#if !defined(NX_SECURE_TLS_SERVER_DISABLED) && defined(NX_SECURE_ENABLE_CLIENT_CERTIFICATE_VERIFY)
    status = nx_secure_tls_session_create(&ssession, &nx_crypto_tls_ciphers, smetadata, sizeof(smetadata));
    if (status)
    {
        printf("  server session create 0x%x\nERROR!\n", status);
        test_control_return(1);
        return;
    }
    s_leg_run("S12 TLS 1.2 server: Certificate + ClientKeyExchange start", _nx_secure_tls_server_handshake,
              NX_SECURE_TLS_CLIENT_KEY_EXCHANGE, 0, 0);
#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    s_leg_run("S13 TLS 1.3 server: Certificate + CertificateVerify start", _nx_secure_tls_1_3_server_handshake,
              NX_SECURE_TLS_CERTIFICATE_VERIFY, 0, 1);
#else
    printf("  S13: N/A, TLS 1.3 is not compiled in\n");
#endif
    s_leg_run("G1 TLS 1.2 server, caller's own buffer", _nx_secure_tls_server_handshake,
              NX_SECURE_TLS_CLIENT_KEY_EXCHANGE, 1, 0);
    s_leg_run("G2 TLS 1.2 server, no session buffer", _nx_secure_tls_server_handshake,
              NX_SECURE_TLS_CLIENT_KEY_EXCHANGE, 2, 0);
#else
    NX_PARAMETER_NOT_USED(smetadata);
    NX_PARAMETER_NOT_USED(sbuffer);
    printf("  S12, S13, G1, G2: N/A, the server or NX_SECURE_ENABLE_CLIENT_CERTIFICATE_VERIFY is not compiled in\n");
#endif

    if (legs_run == 0)
    {
        printf("N/A\n");
        test_control_return(3);
    }
    else if (failures)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_process_record_coalesced_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    printf("NetX Secure Test:   TLS Process Record Coalesced Test..................N/A\n");
    test_control_return(3);
}
#endif
