/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Ownership of handshake packets (N-209, N-210).
   _nx_secure_tls_send_handshake_record() consumes its packet on every return;
   the caller owns it only before the call.  Each leg runs one TLS handshake
   between two IP instances, forces one failure, and checks:
   - the API that drove the failing step returned the code the forced failure
     produced, and the forced failure was that leg's operation, exactly once;
   - every packet of the leg's session pools is back on its free list exactly
     once: nx_packet_pool_available back at the leg's own starting value (no
     packet stranded) and nx_packet_pool_invalid_releases unchanged (no packet
     released twice).
   Each leg gets fresh session pools of its own, never used by another leg, so
   a packet stranded by one leg cannot change the counts of a later leg.
   Failures are forced by defining a library function in this executable, so
   the library's own calls (through its PLT) reach this definition first: a
   builder returns NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL without building, the
   record layer returns NX_NOT_CONNECTED without sending, or the remote
   certificate free returns NX_INVALID_PARAMETERS.  Every other call goes to
   the real function.  Nothing is overrun or corrupted.  */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include   <dlfcn.h>
#include   "tx_api.h"
#include   "nx_api.h"
#include   "nx_secure_tls_api.h"
#include   "nx_secure_tls.h"

extern VOID    test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_TLS_SERVER_DISABLED) && \
    !defined(NX_SECURE_DISABLE_X509) && defined(__linux__)

#include   "test_ca_cert.c"
#include   "test_device_cert.c"
#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
#include   "ecc_certs.c"
#endif

#define STACK_SIZE              4096
#define IP_POOL_PACKETS         40
#define TLS_POOL_PACKETS        16
#define SMALL_PAYLOAD           512
#define METADATA_SIZE           16000
#define SERVER_PORT             4433
#define WAIT_TICKS              (2 * NX_IP_PERIODIC_RATE)
#define LEG_TICKS               (20 * NX_IP_PERIODIC_RATE)

/* What a leg does after a successful handshake. */
#define ACT_START               0
#define ACT_CLIENT_RENEG        1
#define ACT_SERVER_RENEG        2

/* Where the failure is forced. */
#define F_NONE                  0
#define F_CLIENTHELLO           1
#define F_SERVERHELLO           2
#define F_CERTIFICATE           3
#define F_CLIENT_KEY_EXCHANGE   4
#define F_CERTIFICATE_VERIFY    5
#define F_SERVER_KEY_EXCHANGE   6
#define F_ENCRYPTED_EXTENSIONS  7
#define F_FREE_ALL              8
#define F_RECORD_SEND           9

#define SIDE_CLIENT             0
#define SIDE_SERVER             1

#define BUILD_FAIL              NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL
#define SEND_FAIL               NX_NOT_CONNECTED
#define FREE_FAIL               NX_INVALID_PARAMETERS

typedef struct
{
    const CHAR *name;
    UINT        tls_1_3;        /* 0: TLS 1.2, 1: TLS 1.3 */
    UINT        ecc;            /* the ECC table (ECDHE ServerKeyExchange in TLS 1.2) */
    UINT        client_verify;  /* server requests a client certificate */
    UINT        hrr;            /* the client's first key share is a group the server lacks */
    UINT        small_pool;     /* server's packets small enough that Certificate chains */
    UINT        action;
    UINT        fault;
    UINT        side;
    UINT        occurrence;     /* the n-th matching call on that side fails */
    UCHAR       handshake_type; /* for F_RECORD_SEND */
    UINT        expect;         /* status of the failing side's call (both sides for F_NONE) */
} LEG;

/* The failing side's call: nx_secure_tls_session_start for ACT_START,
   nx_secure_tls_session_renegotiate on the side that renegotiates, and
   nx_secure_tls_session_receive on the side that answers it. */
static const LEG legs[] =
{
    /*  name                                         1.3 ecc cv hrr sm action             fault                   side         n  type                               expect */
    { "1.2 success",                                  0,  0, 0, 0,  0, ACT_START,         F_NONE,                 SIDE_CLIENT, 0, 0,                                 NX_SUCCESS },
    { "1.2 session_start ClientHello builder",        0,  0, 0, 0,  0, ACT_START,         F_CLIENTHELLO,          SIDE_CLIENT, 1, 0,                                 BUILD_FAIL },
    { "1.2 session_start ClientHello send",           0,  0, 0, 0,  0, ACT_START,         F_RECORD_SEND,          SIDE_CLIENT, 1, NX_SECURE_TLS_CLIENT_HELLO,        SEND_FAIL },
#ifdef NX_SECURE_ENABLE_CLIENT_CERTIFICATE_VERIFY
    { "1.2 client Certificate builder",               0,  0, 1, 0,  0, ACT_START,         F_CERTIFICATE,          SIDE_CLIENT, 1, 0,                                 BUILD_FAIL },
    { "1.2 client CertificateVerify builder",         0,  0, 1, 0,  0, ACT_START,         F_CERTIFICATE_VERIFY,   SIDE_CLIENT, 1, 0,                                 BUILD_FAIL },
#endif
    { "1.2 client ClientKeyExchange builder",         0,  0, 0, 0,  0, ACT_START,         F_CLIENT_KEY_EXCHANGE,  SIDE_CLIENT, 1, 0,                                 BUILD_FAIL },
    { "1.2 client ClientKeyExchange send",            0,  0, 0, 0,  0, ACT_START,         F_RECORD_SEND,          SIDE_CLIENT, 1, NX_SECURE_TLS_CLIENT_KEY_EXCHANGE, SEND_FAIL },
    { "1.2 server ServerHello builder",               0,  0, 0, 0,  0, ACT_START,         F_SERVERHELLO,          SIDE_SERVER, 1, 0,                                 BUILD_FAIL },
    { "1.2 server ServerHello send",                  0,  0, 0, 0,  0, ACT_START,         F_RECORD_SEND,          SIDE_SERVER, 1, NX_SECURE_TLS_SERVER_HELLO,        SEND_FAIL },
#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
    { "1.2 server ServerKeyExchange builder",         0,  1, 0, 0,  0, ACT_START,         F_SERVER_KEY_EXCHANGE,  SIDE_SERVER, 1, 0,                                 BUILD_FAIL },
#endif
    { "1.2 server Certificate chain send",            0,  0, 0, 0,  1, ACT_START,         F_RECORD_SEND,          SIDE_SERVER, 1, NX_SECURE_TLS_CERTIFICATE_MSG,     SEND_FAIL },
#if !defined(NX_SECURE_TLS_DISABLE_SECURE_RENEGOTIATION)
#if !defined(NX_SECURE_TLS_DISABLE_CLIENT_INITIATED_RENEGOTIATION)
    { "1.2 client renegotiate ClientHello builder",   0,  0, 0, 0,  0, ACT_CLIENT_RENEG,  F_CLIENTHELLO,          SIDE_CLIENT, 2, 0,                                 BUILD_FAIL },
    { "1.2 client renegotiate ClientHello send",      0,  0, 0, 0,  0, ACT_CLIENT_RENEG,  F_RECORD_SEND,          SIDE_CLIENT, 2, NX_SECURE_TLS_CLIENT_HELLO,        SEND_FAIL },
    { "1.2 client renegotiate certificate free",      0,  0, 0, 0,  0, ACT_CLIENT_RENEG,  F_FREE_ALL,             SIDE_CLIENT, 1, 0,                                 FREE_FAIL },
#endif
    { "1.2 server renegotiate HelloRequest send",     0,  0, 0, 0,  0, ACT_SERVER_RENEG,  F_RECORD_SEND,          SIDE_SERVER, 1, NX_SECURE_TLS_HELLO_REQUEST,       SEND_FAIL },
    { "1.2 client HelloRequest ClientHello builder",  0,  0, 0, 0,  0, ACT_SERVER_RENEG,  F_CLIENTHELLO,          SIDE_CLIENT, 2, 0,                                 BUILD_FAIL },
#endif
#if (NX_SECURE_TLS_TLS_1_3_ENABLED) && defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
    { "1.3 success",                                  1,  1, 0, 0,  0, ACT_START,         F_NONE,                 SIDE_CLIENT, 0, 0,                                 NX_SUCCESS },
    { "1.3 HelloRetryRequest success",                1,  1, 0, 1,  0, ACT_START,         F_NONE,                 SIDE_CLIENT, 0, 0,                                 NX_SUCCESS },
    { "1.3 client second ClientHello send",           1,  1, 0, 1,  0, ACT_START,         F_RECORD_SEND,          SIDE_CLIENT, 2, NX_SECURE_TLS_CLIENT_HELLO,        SEND_FAIL },
    { "1.3 client Finished send",                     1,  1, 0, 0,  0, ACT_START,         F_RECORD_SEND,          SIDE_CLIENT, 1, NX_SECURE_TLS_FINISHED,            SEND_FAIL },
    { "1.3 server ServerHello builder",               1,  1, 0, 0,  0, ACT_START,         F_SERVERHELLO,          SIDE_SERVER, 1, 0,                                 BUILD_FAIL },
    { "1.3 server EncryptedExtensions builder",       1,  1, 0, 0,  0, ACT_START,         F_ENCRYPTED_EXTENSIONS, SIDE_SERVER, 1, 0,                                 BUILD_FAIL },
    { "1.3 server HelloRetryRequest builder",         1,  1, 0, 1,  0, ACT_START,         F_SERVERHELLO,          SIDE_SERVER, 1, 0,                                 BUILD_FAIL },
#endif
};

#define LEG_COUNT (sizeof(legs) / sizeof(legs[0]))
#define TLS_AREA  ((TLS_POOL_PACKETS * (1536 + sizeof(NX_PACKET))) / sizeof(ULONG))

static TX_THREAD               sync_thread;
static TX_THREAD               server_thread;
static TX_THREAD               client_thread;
static TX_SEMAPHORE            start_sem[2];
static TX_SEMAPHORE            ready_sem[2];
static TX_SEMAPHORE            go_sem[2];
static TX_SEMAPHORE            end_sem[2];
static NX_PACKET_POOL          ip_pool[2];
static NX_PACKET_POOL          leg_pool[LEG_COUNT][2];     /* [leg][side], never shared between legs */
static ULONG                   leg_pool_area[LEG_COUNT][2][TLS_AREA];
static NX_IP                   ip_0;
static NX_IP                   ip_1;
static NX_TCP_SOCKET           server_socket;
static NX_TCP_SOCKET           client_socket;
static NX_SECURE_TLS_SESSION   server_session;
static NX_SECURE_TLS_SESSION   client_session;
static NX_SECURE_X509_CERT     server_certificate;
static NX_SECURE_X509_CERT     client_certificate;
static NX_SECURE_X509_CERT     client_trusted;
static NX_SECURE_X509_CERT     server_trusted;
static NX_SECURE_X509_CERT     client_remote[2];
static NX_SECURE_X509_CERT     server_remote[2];
static UCHAR                   client_remote_buffer[2][2000];
static UCHAR                   server_remote_buffer[2][2000];
static UCHAR                   server_metadata[METADATA_SIZE];
static UCHAR                   client_metadata[METADATA_SIZE];
static UCHAR                   server_record_buffer[4000];
static UCHAR                   client_record_buffer[4000];
static ULONG                   ip_pool_area[2][(IP_POOL_PACKETS * (1536 + sizeof(NX_PACKET))) / sizeof(ULONG)];
static ULONG                   sync_stack[STACK_SIZE / sizeof(ULONG)];
static ULONG                   server_stack[STACK_SIZE / sizeof(ULONG)];
static ULONG                   client_stack[STACK_SIZE / sizeof(ULONG)];
static ULONG                   ip_stack[2][STACK_SIZE / sizeof(ULONG)];
static ULONG                   arp_area[2][1024 / sizeof(ULONG)];
static UINT                    init_failed;

/* Per-leg state, reset by the sync thread before each leg. */
static UINT                    leg_index;
static UINT                    leg_abort;
static UINT                    setup_status[2];
static UINT                    start_status[2];
static UINT                    result_status[2];
static UINT                    session_created[2];

extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;
#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers_ecc;
extern const USHORT               nx_crypto_ecc_supported_groups[];
extern const NX_CRYPTO_METHOD    *nx_crypto_ecc_curves[];
extern const UINT                 nx_crypto_ecc_supported_groups_size;
extern NX_CRYPTO_METHOD           crypto_method_ec_secp256;
extern NX_CRYPTO_METHOD           crypto_method_ec_secp384;
/* HelloRetryRequest: the client's first group (its only key share) is P-384,
   which the server lacks; the server's P-256 is the client's second. */
static const USHORT               hrr_client_groups[] = { (USHORT)NX_CRYPTO_EC_SECP384R1, (USHORT)NX_CRYPTO_EC_SECP256R1 };
static const NX_CRYPTO_METHOD    *hrr_client_curves[] = { &crypto_method_ec_secp384, &crypto_method_ec_secp256 };
static const USHORT               hrr_server_groups[] = { (USHORT)NX_CRYPTO_EC_SECP256R1 };
static const NX_CRYPTO_METHOD    *hrr_server_curves[] = { &crypto_method_ec_secp256 };
#endif

extern VOID    _nx_ram_network_driver_1500(struct NX_IP_DRIVER_STRUCT *driver_req);
static VOID    sync_entry(ULONG thread_input);
static VOID    side_entry(ULONG side);

/* -----===== the forced failure =====----- */

static const LEG              *current;
static UINT                    fault_calls;
static UINT                    fault_fired;
static UINT                    fired_fault;
static UINT                    fired_side;
static UCHAR                   fired_type;
static UINT                    fault_chain_length;
static UINT                    client_hello_calls;
static UINT                    reneg_armed;    /* the client is inside nx_secure_tls_session_renegotiate */

/* TRUE when this call is the one the leg makes fail. */
static UINT fault_here(UINT fault, NX_SECURE_TLS_SESSION *tls_session, UCHAR type)
{
NX_SECURE_TLS_SESSION *target;

    if ((current == NX_NULL) || (current -> fault != fault))
    {
        return(NX_FALSE);
    }
    target = (current -> side == SIDE_CLIENT) ? &client_session : &server_session;
    if (tls_session != target)
    {
        return(NX_FALSE);
    }

    /* remote_certificate_free_all has callers all through the handshake; the
       one under test is the client's renegotiation.  */
    if ((fault == F_FREE_ALL) && !reneg_armed)
    {
        return(NX_FALSE);
    }
    fault_calls++;
    if (fault_calls != current -> occurrence)
    {
        return(NX_FALSE);
    }
    fault_fired++;
    fired_fault = fault;
    fired_side = current -> side;
    fired_type = type;
    return(NX_TRUE);
}

#define REAL(type, name) static type real_##name; if (real_##name == NX_NULL) { real_##name = (type)dlsym(RTLD_NEXT, #name); }

typedef UINT (*BUILD_FN)(NX_SECURE_TLS_SESSION *, NX_PACKET *);
typedef UINT (*BUILD_WAIT_FN)(NX_SECURE_TLS_SESSION *, NX_PACKET *, ULONG);
typedef UINT (*RECORD_FN)(NX_SECURE_TLS_SESSION *, NX_PACKET *, UCHAR, ULONG);
typedef UINT (*FREE_FN)(NX_SECURE_TLS_SESSION *);

UINT _nx_secure_tls_send_clienthello(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_clienthello);
    if (tls_session == &client_session)
    {
        client_hello_calls++;
    }
    if (fault_here(F_CLIENTHELLO, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_clienthello(tls_session, send_packet));
}

UINT _nx_secure_tls_send_serverhello(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_serverhello);
    if (fault_here(F_SERVERHELLO, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_serverhello(tls_session, send_packet));
}

UINT _nx_secure_tls_send_certificate(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *send_packet,
                                     ULONG wait_option)
{
    REAL(BUILD_WAIT_FN, _nx_secure_tls_send_certificate);
    if (fault_here(F_CERTIFICATE, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_certificate(tls_session, send_packet, wait_option));
}

UINT _nx_secure_tls_send_client_key_exchange(NX_SECURE_TLS_SESSION *tls_session,
                                             NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_client_key_exchange);
    if (fault_here(F_CLIENT_KEY_EXCHANGE, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_client_key_exchange(tls_session, send_packet));
}

UINT _nx_secure_tls_send_certificate_verify(NX_SECURE_TLS_SESSION *tls_session,
                                            NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_certificate_verify);
    if (fault_here(F_CERTIFICATE_VERIFY, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_certificate_verify(tls_session, send_packet));
}

UINT _nx_secure_tls_send_server_key_exchange(NX_SECURE_TLS_SESSION *tls_session,
                                             NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_server_key_exchange);
    if (fault_here(F_SERVER_KEY_EXCHANGE, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_server_key_exchange(tls_session, send_packet));
}

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
UINT _nx_secure_tls_send_encrypted_extensions(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *send_packet)
{
    REAL(BUILD_FN, _nx_secure_tls_send_encrypted_extensions);
    if (fault_here(F_ENCRYPTED_EXTENSIONS, tls_session, 0))
    {
        return(BUILD_FAIL);
    }
    return(real__nx_secure_tls_send_encrypted_extensions(tls_session, send_packet));
}
#endif

UINT _nx_secure_tls_remote_certificate_free_all(NX_SECURE_TLS_SESSION *tls_session)
{
    REAL(FREE_FN, _nx_secure_tls_remote_certificate_free_all);
    if (fault_here(F_FREE_ALL, tls_session, 0))
    {
        return(FREE_FAIL);
    }
    return(real__nx_secure_tls_remote_certificate_free_all(tls_session));
}

/* The record layer is the last step before TCP; failing here without sending
   is what a send to a closed connection looks like to the handshake sender.
   It fails only for the leg's handshake message; alerts and the
   ChangeCipherSpec pass through. */
UINT _nx_secure_tls_send_record(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *send_packet,
                                UCHAR record_type, ULONG wait_option)
{
NX_PACKET *link;

    REAL(RECORD_FN, _nx_secure_tls_send_record);
    if ((record_type == NX_SECURE_TLS_HANDSHAKE) && (current != NX_NULL) &&
        (current -> fault == F_RECORD_SEND) &&
        (send_packet -> nx_packet_prepend_ptr[0] == current -> handshake_type) &&
        fault_here(F_RECORD_SEND, tls_session, send_packet -> nx_packet_prepend_ptr[0]))
    {
        fault_chain_length = 0;
        for (link = send_packet; link != NX_NULL; link = link -> nx_packet_next)
        {
            fault_chain_length++;
        }
        return(SEND_FAIL);
    }
    return(real__nx_secure_tls_send_record(tls_session, send_packet, record_type, wait_option));
}

/* -----===== setup =====----- */

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
void nx_secure_tls_handshake_packet_ownership_test_application_define(void *first_unused_memory)
#endif
{
UINT status;

    NX_PARAMETER_NOT_USED(first_unused_memory);
    init_failed = 0;

    tx_thread_create(&sync_thread, "sync", sync_entry, 0, sync_stack, sizeof(sync_stack),
                     3, 3, TX_NO_TIME_SLICE, TX_AUTO_START);
    tx_thread_create(&server_thread, "server", side_entry, SIDE_SERVER, server_stack, sizeof(server_stack),
                     4, 4, TX_NO_TIME_SLICE, TX_DONT_START);
    tx_thread_create(&client_thread, "client", side_entry, SIDE_CLIENT, client_stack, sizeof(client_stack),
                     5, 5, TX_NO_TIME_SLICE, TX_DONT_START);

    nx_system_initialize();

    status = nx_packet_pool_create(&ip_pool[0], "ip pool 0", 1536, ip_pool_area[0], sizeof(ip_pool_area[0]));
    status += nx_packet_pool_create(&ip_pool[1], "ip pool 1", 1536, ip_pool_area[1], sizeof(ip_pool_area[1]));
    status += nx_ip_create(&ip_0, "server ip", IP_ADDRESS(1, 2, 3, 4), 0xFFFFFF00UL, &ip_pool[0],
                           _nx_ram_network_driver_1500, ip_stack[0], sizeof(ip_stack[0]), 1);
    status += nx_ip_create(&ip_1, "client ip", IP_ADDRESS(1, 2, 3, 5), 0xFFFFFF00UL, &ip_pool[1],
                           _nx_ram_network_driver_1500, ip_stack[1], sizeof(ip_stack[1]), 1);
    status += nx_arp_enable(&ip_0, arp_area[0], sizeof(arp_area[0]));
    status += nx_arp_enable(&ip_1, arp_area[1], sizeof(arp_area[1]));
    status += nx_tcp_enable(&ip_0);
    status += nx_tcp_enable(&ip_1);
    if (status)
    {
        init_failed = 1;
    }

    nx_secure_tls_initialize();
}

/* Stop at the first setup call that fails: report it and return its status. */
#define SETUP(call) do { status = (call); if (status != NX_SUCCESS) { \
    printf("  %s setup failed 0x%x: %s\n", server ? "server" : "client", status, #call); return(status); } } while (0)

static UINT session_setup(const LEG *leg, NX_SECURE_TLS_SESSION *tls_session, UINT server, NX_PACKET_POOL *pool)
{
UINT                        status;
const NX_SECURE_TLS_CRYPTO *table = &nx_crypto_tls_ciphers;

#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
    if (leg -> ecc)
    {
        table = &nx_crypto_tls_ciphers_ecc;
    }
#endif

    SETUP(nx_secure_tls_session_create(tls_session, table, server ? server_metadata : client_metadata,
                                       METADATA_SIZE));
    session_created[server ? SIDE_SERVER : SIDE_CLIENT] = NX_TRUE;

#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
    if (leg -> ecc && leg -> hrr)
    {
        if (server)
        {
            SETUP(nx_secure_tls_ecc_initialize(tls_session, hrr_server_groups, 1, hrr_server_curves));
        }
        else
        {
            SETUP(nx_secure_tls_ecc_initialize(tls_session, hrr_client_groups, 2, hrr_client_curves));
        }
    }
    else if (leg -> ecc)
    {
        SETUP(nx_secure_tls_ecc_initialize(tls_session, nx_crypto_ecc_supported_groups,
                                           (USHORT)nx_crypto_ecc_supported_groups_size,
                                           nx_crypto_ecc_curves));
    }
#endif

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    if (!leg -> tls_1_3)
    {
        SETUP(nx_secure_tls_session_protocol_version_override(tls_session, NX_SECURE_TLS_VERSION_TLS_1_2));
    }
#endif

    SETUP(nx_secure_tls_session_packet_buffer_set(tls_session, server ? server_record_buffer : client_record_buffer,
                                                  server ? sizeof(server_record_buffer) : sizeof(client_record_buffer)));
    SETUP(nx_secure_tls_session_packet_pool_set(tls_session, pool));

    if (server)
    {
#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
        if (leg -> ecc)
        {
            SETUP(nx_secure_x509_certificate_initialize(&server_certificate, ECTestServer2_der, ECTestServer2_der_len,
                                                        NX_NULL, 0, ECTestServer2_key_der, ECTestServer2_key_der_len,
                                                        NX_SECURE_X509_KEY_TYPE_EC_DER));
        }
        else
#endif
        {
            SETUP(nx_secure_x509_certificate_initialize(&server_certificate, test_device_cert_der, test_device_cert_der_len,
                                                        NX_NULL, 0, test_device_cert_key_der, test_device_cert_key_der_len,
                                                        NX_SECURE_X509_KEY_TYPE_RSA_PKCS1_DER));
        }
        SETUP(nx_secure_tls_local_certificate_add(tls_session, &server_certificate));
#ifdef NX_SECURE_ENABLE_CLIENT_CERTIFICATE_VERIFY
        if (leg -> client_verify)
        {
            SETUP(nx_secure_tls_session_client_verify_enable(tls_session));
            SETUP(nx_secure_tls_remote_certificate_allocate(tls_session, &server_remote[0], server_remote_buffer[0],
                                                            sizeof(server_remote_buffer[0])));
            SETUP(nx_secure_tls_remote_certificate_allocate(tls_session, &server_remote[1], server_remote_buffer[1],
                                                            sizeof(server_remote_buffer[1])));
            SETUP(nx_secure_x509_certificate_initialize(&server_trusted, test_ca_cert_der, test_ca_cert_der_len,
                                                        NX_NULL, 0, NX_NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE));
            SETUP(nx_secure_tls_trusted_certificate_add(tls_session, &server_trusted));
        }
#endif
    }
    else
    {
        SETUP(nx_secure_tls_remote_certificate_allocate(tls_session, &client_remote[0], client_remote_buffer[0],
                                                        sizeof(client_remote_buffer[0])));
        SETUP(nx_secure_tls_remote_certificate_allocate(tls_session, &client_remote[1], client_remote_buffer[1],
                                                        sizeof(client_remote_buffer[1])));
#if defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE)
        if (leg -> ecc)
        {
            SETUP(nx_secure_x509_certificate_initialize(&client_trusted, ECCA2_der, ECCA2_der_len,
                                                        NX_NULL, 0, NX_NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE));
        }
        else
#endif
        {
            SETUP(nx_secure_x509_certificate_initialize(&client_trusted, test_ca_cert_der, test_ca_cert_der_len,
                                                        NX_NULL, 0, NX_NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE));
        }
        SETUP(nx_secure_tls_trusted_certificate_add(tls_session, &client_trusted));
        if (leg -> client_verify)
        {
            SETUP(nx_secure_x509_certificate_initialize(&client_certificate, test_device_cert_der, test_device_cert_der_len,
                                                        NX_NULL, 0, test_device_cert_key_der, test_device_cert_key_der_len,
                                                        NX_SECURE_X509_KEY_TYPE_RSA_PKCS1_DER));
            SETUP(nx_secure_tls_local_certificate_add(tls_session, &client_certificate));
        }
    }
    return(NX_SUCCESS);
}

/* -----===== the legs =====----- */

static VOID sync_entry(ULONG thread_input)
{
UINT            i;
UINT            side;
UINT            ok_pool;
UINT            ok_status;
UINT            ok_fault;
UINT            ok_extra;
UINT            failures = 0;
ULONG           available[2];
ULONG           invalid[2];
NX_PACKET_POOL *pool;
const LEG      *leg;

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Secure Test:   TLS Handshake Packet Ownership Test................\n");

    if (init_failed)
    {
        printf("  IP setup failed\nERROR!\n");
        test_control_return(1);
        return;
    }
    for (side = 0; side < 2; side++)
    {
        tx_semaphore_create(&start_sem[side], "start", 0);
        tx_semaphore_create(&ready_sem[side], "ready", 0);
        tx_semaphore_create(&go_sem[side], "go", 0);
        tx_semaphore_create(&end_sem[side], "end", 0);
    }
    tx_thread_resume(&server_thread);
    tx_thread_resume(&client_thread);

    for (i = 0; i < LEG_COUNT; i++)
    {
        leg = &legs[i];

        /* This leg's own pools: fresh, used by no other leg. */
        if ((nx_packet_pool_create(&leg_pool[i][SIDE_CLIENT], "leg client pool", 1536,
                                   leg_pool_area[i][SIDE_CLIENT], sizeof(leg_pool_area[i][SIDE_CLIENT])) != NX_SUCCESS) ||
            (nx_packet_pool_create(&leg_pool[i][SIDE_SERVER], "leg server pool",
                                   leg -> small_pool ? SMALL_PAYLOAD : 1536,
                                   leg_pool_area[i][SIDE_SERVER], sizeof(leg_pool_area[i][SIDE_SERVER])) != NX_SUCCESS))
        {
            printf("  leg %2u %-44s FAIL  pool create\n", i + 1, leg -> name);
            failures++;
            continue;
        }
        for (side = 0; side < 2; side++)
        {
            available[side] = leg_pool[i][side].nx_packet_pool_available;
            invalid[side] = leg_pool[i][side].nx_packet_pool_invalid_releases;
            setup_status[side] = NX_SUCCESS;
            start_status[side] = NX_SUCCESS;
            result_status[side] = NX_SUCCESS;
            session_created[side] = NX_FALSE;
        }
        fault_calls = 0;
        fault_fired = 0;
        fired_fault = F_NONE;
        fired_side = 0;
        fired_type = 0;
        fault_chain_length = 0;
        client_hello_calls = 0;
        leg_abort = NX_FALSE;
        leg_index = i;
        current = leg;

        /* Both sides set up; the handshake runs only if both setups succeeded. */
        tx_semaphore_put(&start_sem[SIDE_SERVER]);
        tx_semaphore_put(&start_sem[SIDE_CLIENT]);
        if ((tx_semaphore_get(&ready_sem[SIDE_SERVER], LEG_TICKS) != TX_SUCCESS) ||
            (tx_semaphore_get(&ready_sem[SIDE_CLIENT], LEG_TICKS) != TX_SUCCESS))
        {
            printf("  leg %2u %-44s FAIL  setup did not finish; stopping\nERROR!\n", i + 1, leg -> name);
            test_control_return(1);
            return;
        }
        if ((setup_status[SIDE_SERVER] != NX_SUCCESS) || (setup_status[SIDE_CLIENT] != NX_SUCCESS))
        {
            leg_abort = NX_TRUE;
        }
        tx_semaphore_put(&go_sem[SIDE_SERVER]);
        tx_semaphore_put(&go_sem[SIDE_CLIENT]);
        if ((tx_semaphore_get(&end_sem[SIDE_CLIENT], LEG_TICKS) != TX_SUCCESS) ||
            (tx_semaphore_get(&end_sem[SIDE_SERVER], LEG_TICKS) != TX_SUCCESS))
        {
            printf("  leg %2u %-44s FAIL  handshake did not finish; stopping\nERROR!\n", i + 1, leg -> name);
            test_control_return(1);
            return;
        }
        tx_thread_sleep(NX_IP_PERIODIC_RATE / 10);
        current = NX_NULL;

        if (leg_abort)
        {
            printf("  leg %2u %-44s FAIL  setup: server 0x%x client 0x%x; handshake not run\n",
                   i + 1, leg -> name, setup_status[SIDE_SERVER], setup_status[SIDE_CLIENT]);
            failures++;
            continue;
        }

        /* Packets: each pool back at this leg's own starting count, no release twice. */
        ok_pool = NX_TRUE;
        for (side = 0; side < 2; side++)
        {
            pool = &leg_pool[i][side];
            if ((pool -> nx_packet_pool_available != available[side]) ||
                (pool -> nx_packet_pool_invalid_releases != invalid[side]))
            {
                ok_pool = NX_FALSE;
            }
        }

        /* Status: the failing side's call returned the forced code; a success leg
           succeeded on both sides.  A renegotiation needs a completed handshake first. */
        if (leg -> fault == F_NONE)
        {
            ok_status = (result_status[SIDE_CLIENT] == NX_SUCCESS) && (result_status[SIDE_SERVER] == NX_SUCCESS);
        }
        else
        {
            ok_status = (result_status[leg -> side] == leg -> expect);
        }
        if (leg -> action != ACT_START)
        {
            ok_status = ok_status && (start_status[SIDE_CLIENT] == NX_SUCCESS) &&
                        (start_status[SIDE_SERVER] == NX_SUCCESS);
        }

        /* Operation: the leg's own failure fired, once, on the leg's side and message. */
        if (leg -> fault == F_NONE)
        {
            ok_fault = (fault_fired == 0);
        }
        else
        {
            ok_fault = (fault_fired == 1) && (fired_fault == leg -> fault) && (fired_side == leg -> side) &&
                       (fired_type == ((leg -> fault == F_RECORD_SEND) ? leg -> handshake_type : 0));
        }

        /* A HelloRetryRequest leg sent two ClientHellos; a small-pool send was a chain. */
        ok_extra = NX_TRUE;
        if (leg -> hrr && (leg -> side == SIDE_CLIENT))
        {
            ok_extra = (client_hello_calls == 2);
        }
        if (leg -> small_pool && (leg -> fault == F_RECORD_SEND))
        {
            ok_extra = (fault_chain_length > 1);
        }

        printf("  leg %2u %-44s %s  status %s (client 0x%x server 0x%x, expect 0x%x)  fault %s (fired %u op %u type %u)"
               "  pools %s (client %lu/%lu inv %lu, server %lu/%lu inv %lu)  extra %s (hello %u chain %u)\n",
               i + 1, leg -> name, (ok_pool && ok_status && ok_fault && ok_extra) ? "PASS" : "FAIL",
               ok_status ? "ok" : "BAD", result_status[SIDE_CLIENT], result_status[SIDE_SERVER], leg -> expect,
               ok_fault ? "ok" : "BAD", fault_fired, fired_fault, fired_type,
               ok_pool ? "ok" : "BAD",
               leg_pool[i][SIDE_CLIENT].nx_packet_pool_available, available[SIDE_CLIENT],
               leg_pool[i][SIDE_CLIENT].nx_packet_pool_invalid_releases - invalid[SIDE_CLIENT],
               leg_pool[i][SIDE_SERVER].nx_packet_pool_available, available[SIDE_SERVER],
               leg_pool[i][SIDE_SERVER].nx_packet_pool_invalid_releases - invalid[SIDE_SERVER],
               ok_extra ? "ok" : "BAD", client_hello_calls, fault_chain_length);
        if (!(ok_pool && ok_status && ok_fault && ok_extra))
        {
            failures++;
        }
    }

    if (failures)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* One side of one leg: set up, wait for the go, run the leg's calls, tear down. */
static VOID side_run(const LEG *leg, UINT side)
{
UINT                   server = (side == SIDE_SERVER);
UINT                   status;
#if !defined(NX_SECURE_TLS_DISABLE_SECURE_RENEGOTIATION)
NX_PACKET             *packet;
#endif
NX_TCP_SOCKET         *socket_ptr = server ? &server_socket : &client_socket;
NX_SECURE_TLS_SESSION *session = server ? &server_session : &client_session;

    /* Setup: the socket, then the session. */
    status = nx_tcp_socket_create(server ? &ip_0 : &ip_1, socket_ptr, "socket", NX_IP_NORMAL, NX_FRAGMENT_OKAY,
                                  NX_IP_TIME_TO_LIVE, 16 * 1024, NX_NULL, NX_NULL);
    if (status != NX_SUCCESS)
    {
        printf("  %s setup failed 0x%x: nx_tcp_socket_create\n", server ? "server" : "client", status);
        setup_status[side] = status;
        tx_semaphore_put(&ready_sem[side]);
        tx_semaphore_get(&go_sem[side], TX_WAIT_FOREVER);
        return;
    }
    if (server)
    {
        status = nx_tcp_server_socket_listen(&ip_0, SERVER_PORT, socket_ptr, 5, NX_NULL);
    }
    else
    {
        status = nx_tcp_client_socket_bind(socket_ptr, NX_ANY_PORT, NX_IP_PERIODIC_RATE);
    }
    if (status != NX_SUCCESS)
    {
        printf("  %s setup failed 0x%x: %s\n", server ? "server" : "client", status,
               server ? "nx_tcp_server_socket_listen" : "nx_tcp_client_socket_bind");
    }
    else
    {
        status = session_setup(leg, session, server, &leg_pool[leg_index][side]);
    }
    setup_status[side] = status;
    tx_semaphore_put(&ready_sem[side]);
    tx_semaphore_get(&go_sem[side], TX_WAIT_FOREVER);

    if (!leg_abort)
    {
        if (server)
        {
            status = nx_tcp_server_socket_accept(socket_ptr, WAIT_TICKS);
        }
        else
        {
            status = nx_tcp_client_socket_connect(socket_ptr, IP_ADDRESS(1, 2, 3, 4), SERVER_PORT, WAIT_TICKS);
        }
        if (status != NX_SUCCESS)
        {
            printf("  %s connect failed 0x%x\n", server ? "server" : "client", status);
            start_status[side] = status;
            result_status[side] = status;
        }
        else
        {
            status = nx_secure_tls_session_start(session, socket_ptr, WAIT_TICKS);
            start_status[side] = status;
            result_status[side] = status;
#if !defined(NX_SECURE_TLS_DISABLE_SECURE_RENEGOTIATION)
            if ((status == NX_SUCCESS) && (leg -> action != ACT_START))
            {
                if (((leg -> action == ACT_CLIENT_RENEG) && !server) ||
                    ((leg -> action == ACT_SERVER_RENEG) && server))
                {
                    reneg_armed = !server;
                    result_status[side] = nx_secure_tls_session_renegotiate(session, WAIT_TICKS);
                    reneg_armed = NX_FALSE;
                }
                else
                {
                    result_status[side] = nx_secure_tls_session_receive(session, &packet, WAIT_TICKS);
                    if (result_status[side] == NX_SUCCESS)
                    {
                        nx_packet_release(packet);
                    }
                }
            }
#endif
            nx_secure_tls_session_end(session, NX_NO_WAIT);
        }
    }

    if (session_created[side])
    {
        nx_secure_tls_session_delete(session);
    }
    nx_tcp_socket_disconnect(socket_ptr, NX_IP_PERIODIC_RATE);
    if (server)
    {
        nx_tcp_server_socket_unaccept(socket_ptr);
        nx_tcp_server_socket_unlisten(&ip_0, SERVER_PORT);
    }
    else
    {
        nx_tcp_client_socket_unbind(socket_ptr);
    }
    nx_tcp_socket_delete(socket_ptr);
}

static VOID side_entry(ULONG side)
{
UINT i;

    for (i = 0; i < LEG_COUNT; i++)
    {
        tx_semaphore_get(&start_sem[side], TX_WAIT_FOREVER);
        side_run(&legs[leg_index], (UINT)side);
        tx_semaphore_put(&end_sem[side]);
    }
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_handshake_packet_ownership_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    printf("NetX Secure Test:   TLS Handshake Packet Ownership Test................N/A\n");
    test_control_return(3);
}
#endif
