/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* The record cursor across a handshake message fragmented over several
   records (N-212).  One 96-byte Certificate message is sent as two or three
   records, and the records are queued as one or two TCP packets.  Each leg
   drives _nx_secure_tls_process_record() directly, the way
   nx_secure_tls_session_receive_records() does, and checks every call's
   status, the saved cursor (nx_secure_tls_record_offset and
   nx_secure_tls_bytes_processed) after an NX_CONTINUE, bytes_processed after
   NX_SUCCESS, the fragment state, the reassembled message byte for byte, the
   remote sequence number, and that the leg's own packet pool is whole again
   after the queue is released.

   Decryption and the handshake state machine are replaced by defining the
   library functions in this executable (the library's own calls reach them
   through its PLT):
   - _nx_secure_tls_record_payload_decrypt returns the wire payload without
     the AEAD framing (TLS 1.2: 8-byte explicit nonce and 16-byte tag;
     TLS 1.3: 16-byte tag), so plaintext is shorter than the record as on the
     wire, which is what moves the cursor;
   - the client state machines follow the vendor's fragment rule
     (nx_secure_tls_1_3_client_handshake.c:215-222) and keep the completed
     message.
   So this proves the record layer's cursor, state and cleanup.  It does not
   prove authenticated end-to-end decryption.  Every record is well formed.  */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include   <dlfcn.h>
#include   <string.h>
#include   "tx_api.h"
#include   "nx_api.h"
#include   "nx_secure_tls_api.h"
#include   "nx_secure_tls.h"

extern VOID    test_control_return(UINT status);
extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && defined(__linux__)

#define METADATA_SIZE       16000
#define LEG_PACKETS         8
#define PACKET_SIZE         1536
#define POOL_AREA           ((LEG_PACKETS * (PACKET_SIZE + sizeof(NX_PACKET))) / sizeof(ULONG))
#define MESSAGE_LENGTH      96          /* 4-byte handshake header + 92 */
#define MAX_RECORDS         3
#define MAX_CALLS           2

#define KIND_PLAIN          0           /* no record protection */
#define KIND_TLS12          1           /* TLS 1.2 after ChangeCipherSpec, AEAD framing */
#define KIND_TLS13          2           /* TLS 1.3, outer type application data */

#define TLS12_NONCE         8
#define AEAD_TAG            16

typedef struct
{
    const CHAR *name;
    UINT        kind;
    UINT        fragments[MAX_RECORDS]; /* bytes of the message in each record; 0 ends */
    INT         cut;                    /* queue split: -1 none, else bytes from the end of record 2 (+) */
    UINT        calls;                  /* calls expected */
    UINT        status[MAX_CALLS];      /* expected status per call */
    ULONG       saved;                  /* expected saved offset == bytes_processed after the NX_CONTINUE */
    ULONG       total;                  /* expected bytes_processed with NX_SUCCESS */
    UINT        sequence;               /* expected remote sequence number at the end */
} LEG;

#define CUT_NONE        (-1000)

/* cut: where the first TCP packet ends, as an offset from the end of the
   second record (0 = exactly there, 3 = three bytes into the third record's
   header, -1000 = one packet); first_only cuts after the first record. */
typedef struct
{
    LEG  leg;
    UINT cut_after_first;
} LEG_ROW;

static const LEG_ROW legs[] =
{
    /* name                                        kind         fragments     cut       calls status                          saved total seq   first */
    {{ "P1 plaintext, one packet",                 KIND_PLAIN, {40, 32, 24}, CUT_NONE, 1, {NX_SUCCESS, 0},                   0,    111,  0 }, 0 },
    {{ "P2 plaintext, middle ends the packet",     KIND_PLAIN, {40, 32, 24}, 0,        2, {NX_CONTINUE, NX_SUCCESS},         82,   111,  0 }, 0 },
    {{ "P3 plaintext, first ends the packet",      KIND_PLAIN, {40, 32, 24}, 0,        2, {NX_CONTINUE, NX_SUCCESS},         45,   111,  0 }, 1 },
    {{ "P4 plaintext, packet ends inside a header",KIND_PLAIN, {40, 32, 24}, 3,        2, {NX_CONTINUE, NX_SUCCESS},         82,   111,  0 }, 0 },
#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    {{ "E1 TLS 1.3, one packet",                   KIND_TLS13, {40, 32, 24}, CUT_NONE, 1, {NX_SUCCESS, 0},                   0,    162,  3 }, 0 },
    {{ "E2 TLS 1.3, middle ends the packet",       KIND_TLS13, {40, 32, 24}, 0,        2, {NX_CONTINUE, NX_SUCCESS},         116,  162,  3 }, 0 },
#endif
    {{ "E3 TLS 1.2 encrypted, middle ends packet", KIND_TLS12, {40, 32, 24}, 0,        2, {NX_CONTINUE, NX_SUCCESS},         130,  183,  3 }, 0 },
#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    {{ "E4 TLS 1.3, two records (control)",        KIND_TLS13, {40, 56, 0},  CUT_NONE, 1, {NX_SUCCESS, 0},                   0,    140,  2 }, 0 },
#endif
};

#define LEG_COUNT (sizeof(legs) / sizeof(legs[0]))

static NX_SECURE_TLS_SESSION   session;
static UCHAR                   session_metadata[METADATA_SIZE];
static UCHAR                   record_buffer[4000];
static NX_PACKET_POOL          leg_pool[LEG_COUNT];
static ULONG                   leg_pool_area[LEG_COUNT][POOL_AREA];
static NX_SECURE_TLS_CIPHERSUITE_INFO test_ciphersuite;
static UCHAR                   message[MESSAGE_LENGTH];
static UCHAR                   stream[600];
static UCHAR                   scratch[600];

/* What the replaced functions saw. */
static UINT                    active_kind;
static UINT                    machine_calls;
static UINT                    machine_armed;
static UINT                    delivered_length;
static UCHAR                   delivered[MESSAGE_LENGTH];
static UINT                    decrypt_calls;

/* -----===== the replaced functions =====----- */

typedef UINT (*DECRYPT_FN)(NX_SECURE_TLS_SESSION *, NX_PACKET *, UINT, UINT, NX_PACKET **,
                           ULONG *, UCHAR, UINT);

UINT _nx_secure_tls_record_payload_decrypt(NX_SECURE_TLS_SESSION *tls_session, NX_PACKET *encrypted_packet,
                                           UINT offset, UINT message_length, NX_PACKET **decrypted_packet,
                                           ULONG sequence_num[NX_SECURE_TLS_SEQUENCE_NUMBER_SIZE],
                                           UCHAR record_type, UINT wait_option)
{
static DECRYPT_FN real_decrypt;
NX_PACKET *packet;
ULONG      copied;
UINT       skip = (active_kind == KIND_TLS12) ? TLS12_NONCE : 0;
UINT       length;
UINT       status;

    if (tls_session != &session)
    {
        if (real_decrypt == NX_NULL)
        {
            real_decrypt = (DECRYPT_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_record_payload_decrypt");
        }
        return(real_decrypt(tls_session, encrypted_packet, offset, message_length, decrypted_packet,
                            sequence_num, record_type, wait_option));
    }

    decrypt_calls++;
    if (message_length < skip + AEAD_TAG)
    {
        return(NX_SECURE_TLS_INVALID_PACKET);
    }
    length = message_length - skip - AEAD_TAG;
    if (nx_packet_data_extract_offset(encrypted_packet, offset + skip, scratch, length, &copied) ||
        (copied != length))
    {
        return(NX_SECURE_TLS_INVALID_PACKET);
    }
    status = nx_packet_allocate(tls_session -> nx_secure_tls_packet_pool, &packet, NX_IPv4_TCP_PACKET, NX_NO_WAIT);
    if (status)
    {
        return(status);
    }
    status = nx_packet_data_append(packet, scratch, length, tls_session -> nx_secure_tls_packet_pool, NX_NO_WAIT);
    if (status)
    {
        nx_packet_release(packet);
        return(status);
    }
    *decrypted_packet = packet;
    return(NX_SECURE_TLS_SUCCESS);
}

/* The vendor's fragment rule, then keep the completed message. */
static UINT machine(NX_SECURE_TLS_SESSION *tls_session, UCHAR *packet_buffer, UINT data_length)
{
UINT total;

    machine_calls++;
    if (data_length < 4)
    {
        return(NX_SECURE_TLS_INVALID_PACKET);
    }
    total = 4 + (((UINT)packet_buffer[1] << 16) | ((UINT)packet_buffer[2] << 8) | packet_buffer[3]);
    if (total > data_length)
    {
        machine_armed++;
        tls_session -> nx_secure_tls_handshake_record_expected_length = total;
        tls_session -> nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_RECEIVED_FRAGMENT;
        return(NX_SECURE_TLS_HANDSHAKE_FRAGMENT_RECEIVED);
    }
    delivered_length = (data_length > MESSAGE_LENGTH) ? MESSAGE_LENGTH : data_length;
    memcpy(delivered, packet_buffer, delivered_length);
    return(NX_SUCCESS);
}

typedef UINT (*MACHINE_FN)(NX_SECURE_TLS_SESSION *, UCHAR *, UINT, ULONG);

UINT _nx_secure_tls_client_handshake(NX_SECURE_TLS_SESSION *tls_session, UCHAR *packet_buffer,
                                     UINT data_length, ULONG wait_option)
{
static MACHINE_FN real_machine;

    if (tls_session != &session)
    {
        if (real_machine == NX_NULL)
        {
            real_machine = (MACHINE_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_client_handshake");
        }
        return(real_machine(tls_session, packet_buffer, data_length, wait_option));
    }
    return(machine(tls_session, packet_buffer, data_length));
}

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
UINT _nx_secure_tls_1_3_client_handshake(NX_SECURE_TLS_SESSION *tls_session, UCHAR *packet_buffer,
                                         UINT data_length, ULONG wait_option)
{
static MACHINE_FN real_machine;

    if (tls_session != &session)
    {
        if (real_machine == NX_NULL)
        {
            real_machine = (MACHINE_FN)dlsym(RTLD_NEXT, "_nx_secure_tls_1_3_client_handshake");
        }
        return(real_machine(tls_session, packet_buffer, data_length, wait_option));
    }
    return(machine(tls_session, packet_buffer, data_length));
}
#endif

/* TLS 1.2 record MAC: AEAD has none to strip; count the record as the real one does. */
static UINT verify_mac_none(const NX_SECURE_TLS_CIPHERSUITE_INFO *ciphersuite, UCHAR *mac_secret,
                            ULONG sequence_num[NX_SECURE_TLS_SEQUENCE_NUMBER_SIZE],
                            UCHAR *header_data, USHORT header_length,
                            NX_PACKET *packet_ptr, ULONG offset, UINT *length,
                            VOID *hash_mac_metadata, ULONG hash_mac_metadata_size)
{
    NX_PARAMETER_NOT_USED(ciphersuite);
    NX_PARAMETER_NOT_USED(mac_secret);
    NX_PARAMETER_NOT_USED(header_data);
    NX_PARAMETER_NOT_USED(header_length);
    NX_PARAMETER_NOT_USED(packet_ptr);
    NX_PARAMETER_NOT_USED(offset);
    NX_PARAMETER_NOT_USED(length);
    NX_PARAMETER_NOT_USED(hash_mac_metadata);
    NX_PARAMETER_NOT_USED(hash_mac_metadata_size);
    sequence_num[0]++;
    return(NX_SECURE_TLS_SUCCESS);
}

/* -----===== records =====----- */

/* One record carrying fragment bytes [from, from + length) of the message. */
static UINT record_put(UCHAR *out, UINT kind, UINT from, UINT length)
{
UINT wire;
UINT at = 5;

    if (kind == KIND_TLS13)
    {
        wire = length + 1 + AEAD_TAG;
    }
    else if (kind == KIND_TLS12)
    {
        wire = TLS12_NONCE + length + AEAD_TAG;
    }
    else
    {
        wire = length;
    }

    out[0] = (kind == KIND_TLS13) ? NX_SECURE_TLS_APPLICATION_DATA : NX_SECURE_TLS_HANDSHAKE;
    out[1] = 0x03;
    out[2] = 0x03;
    out[3] = (UCHAR)(wire >> 8);
    out[4] = (UCHAR)wire;
    memset(&out[5], 0, wire);
    if (kind == KIND_TLS12)
    {
        at += TLS12_NONCE;
    }
    memcpy(&out[at], &message[from], length);
    if (kind == KIND_TLS13)
    {
        out[at + length] = NX_SECURE_TLS_HANDSHAKE;    /* inner content type */
    }
    return(5 + wire);
}

static UINT queue_packet(NX_PACKET_POOL *pool, NX_PACKET **packet, UCHAR *data, UINT length)
{
UINT status;

    status = nx_packet_allocate(pool, packet, NX_IPv4_TCP_PACKET, NX_NO_WAIT);
    if (status == NX_SUCCESS)
    {
        status = nx_packet_data_append(*packet, data, length, pool, NX_NO_WAIT);
        if (status != NX_SUCCESS)
        {
            nx_packet_release(*packet);
        }
    }
    return(status);
}

/* -----===== the legs =====----- */

static UINT run_leg(UINT index)
{
const LEG_ROW *row = &legs[index];
const LEG     *leg = &row -> leg;
NX_PACKET_POOL *pool = &leg_pool[index];
NX_PACKET     *packet;
UINT           records[MAX_RECORDS];
UINT           count = 0;
UINT           length = 0;
UINT           from = 0;
UINT           cut;
UINT           pieces;
UINT           call;
UINT           status;
UINT           ok = NX_TRUE;
ULONG          bytes_processed;
ULONG          available;
ULONG          invalid;

    if (nx_packet_pool_create(pool, "leg pool", PACKET_SIZE, leg_pool_area[index], sizeof(leg_pool_area[index])))
    {
        printf("  %-44s FAIL pool create\n", leg -> name);
        return(NX_FALSE);
    }
    available = pool -> nx_packet_pool_available;
    invalid = pool -> nx_packet_pool_invalid_releases;

    /* The byte stream. */
    while ((count < MAX_RECORDS) && leg -> fragments[count])
    {
        records[count] = record_put(&stream[length], leg -> kind, from, leg -> fragments[count]);
        from += leg -> fragments[count];
        length += records[count];
        count++;
    }
    if (leg -> cut == CUT_NONE)
    {
        cut = length;
    }
    else if (row -> cut_after_first)
    {
        cut = records[0] + (UINT)leg -> cut;
    }
    else
    {
        cut = records[0] + records[1] + (UINT)leg -> cut;
    }
    pieces = (cut < length) ? 2 : 1;

    /* A fresh session state for this leg. */
    session.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_CLIENT;
    session.nx_secure_tls_client_state = NX_SECURE_TLS_CLIENT_STATE_SERVERHELLO;
    session.nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_2;
    session.nx_secure_tls_packet_pool = pool;
    session.nx_secure_tls_packet_buffer = record_buffer;
    session.nx_secure_tls_packet_buffer_size = sizeof(record_buffer);
    session.nx_secure_record_queue_header = NX_NULL;
    session.nx_secure_record_decrypted_packet = NX_NULL;
    session.nx_secure_tls_record_offset = 0;
    session.nx_secure_tls_bytes_processed = 0;
    session.nx_secure_tls_packet_buffer_bytes_copied = 0;
    session.nx_secure_tls_handshake_record_expected_length = 0;
    session.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;
    session.nx_secure_tls_remote_sequence_number[0] = 0;
    session.nx_secure_tls_remote_sequence_number[1] = 0;
    session.nx_secure_tls_remote_session_active = (leg -> kind != KIND_PLAIN);
    session.nx_secure_tls_session_ciphersuite = &test_ciphersuite;
    session.nx_secure_tls_encrypt_then_mac = NX_FALSE;
    session.nx_secure_verify_mac = verify_mac_none;
#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    session.nx_secure_tls_1_3 = (leg -> kind == KIND_TLS13);
#endif
    memset(record_buffer, 0, sizeof(record_buffer));
    active_kind = leg -> kind;
    machine_calls = 0;
    machine_armed = 0;
    delivered_length = 0;
    memset(delivered, 0, sizeof(delivered));
    decrypt_calls = 0;

    printf("  %s: %u records %u bytes, TCP packets %u", leg -> name, count, length, pieces);
    if (pieces == 2)
    {
        printf(" [%u][%u]", cut, length - cut);
    }
    printf("\n");

    for (call = 0; call < pieces; call++)
    {
        status = queue_packet(pool, &packet, call ? &stream[cut] : stream, call ? (length - cut) : cut);
        if (status)
        {
            printf("    call %u: packet 0x%x\n", call + 1, status);
            ok = NX_FALSE;
            break;
        }
        bytes_processed = 0xDEADBEEF;
        status = _nx_secure_tls_process_record(&session, packet, &bytes_processed, NX_NO_WAIT);
        printf("    call %u: status 0x%x bytes_processed %lu session record_offset %lu session bytes_processed %lu fragment_state %u copied %lu"
               " machine %u armed %u decrypt %u sequence %lu\n",
               call + 1, status, bytes_processed, session.nx_secure_tls_record_offset,
               session.nx_secure_tls_bytes_processed,
               (UINT)session.nx_secure_tls_handshake_record_fragment_state,
               session.nx_secure_tls_packet_buffer_bytes_copied, machine_calls, machine_armed, decrypt_calls,
               session.nx_secure_tls_remote_sequence_number[0]);

        if ((call >= leg -> calls) || (status != leg -> status[call]))
        {
            printf("    call %u: expected status 0x%x\n", call + 1, (call < leg -> calls) ? leg -> status[call] : 0);
            ok = NX_FALSE;
        }
        else if ((status == NX_CONTINUE) &&
                 ((session.nx_secure_tls_record_offset != leg -> saved) ||
                  (session.nx_secure_tls_bytes_processed != leg -> saved)))
        {
            printf("    call %u: expected saved offset and bytes %lu\n", call + 1, leg -> saved);
            ok = NX_FALSE;
        }

        /* Only NX_CONTINUE asks for the next TCP packet. */
        if (status != NX_CONTINUE)
        {
            call++;
            break;
        }
    }

    if (ok)
    {
        if ((call != leg -> calls) || (status != NX_SUCCESS) || (bytes_processed != leg -> total) ||
            (session.nx_secure_tls_record_offset != 0) ||
            (session.nx_secure_tls_handshake_record_fragment_state != NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT) ||
            (machine_armed != 1) || (delivered_length != MESSAGE_LENGTH) ||
            memcmp(delivered, message, MESSAGE_LENGTH) ||
            (session.nx_secure_tls_remote_sequence_number[0] != leg -> sequence))
        {
            printf("    end: expected bytes_processed %lu, saved offset 0, no fragment, armed 1, message %u bytes"
                   " (got %u, %s), sequence %u\n", leg -> total, MESSAGE_LENGTH, delivered_length,
                   memcmp(delivered, message, MESSAGE_LENGTH) ? "differs" : "same", leg -> sequence);
            ok = NX_FALSE;
        }
    }

    /* Release what the session still holds: the queue and a decrypted record. */
    if (session.nx_secure_record_decrypted_packet)
    {
        nx_packet_release(session.nx_secure_record_decrypted_packet);
        session.nx_secure_record_decrypted_packet = NX_NULL;
    }
    if (session.nx_secure_record_queue_header)
    {
        nx_packet_release(session.nx_secure_record_queue_header);
        session.nx_secure_record_queue_header = NX_NULL;
    }
    session.nx_secure_tls_record_offset = 0;
    session.nx_secure_tls_bytes_processed = 0;
    session.nx_secure_tls_handshake_record_fragment_state = NX_SECURE_TLS_HANDSHAKE_NO_FRAGMENT;

    printf("    pool %lu/%lu invalid_releases %lu\n", pool -> nx_packet_pool_available, available,
           pool -> nx_packet_pool_invalid_releases - invalid);
    if ((pool -> nx_packet_pool_available != available) ||
        (pool -> nx_packet_pool_invalid_releases != invalid))
    {
        ok = NX_FALSE;
    }
    printf("  %-44s %s\n", leg -> name, ok ? "PASS" : "FAIL");
    return(ok);
}

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_process_record_fragment_test_application_define(void *first_unused_memory)
#endif
{
UINT i;
UINT failures = 0;
UINT status;

    NX_PARAMETER_NOT_USED(first_unused_memory);

    printf("NetX Secure Test:   TLS Process Record Fragment Test...................\n");
#if !(NX_SECURE_TLS_TLS_1_3_ENABLED)
    printf("  E1, E2, E4: N/A, TLS 1.3 is not compiled in\n");
#endif

    /* A Certificate message: type, 24-bit length 92, then zeros. */
    memset(message, 0, sizeof(message));
    message[0] = NX_SECURE_TLS_CERTIFICATE_MSG;
    message[3] = MESSAGE_LENGTH - 4;

    memset(session_metadata, 0, sizeof(session_metadata));
    status = nx_secure_tls_session_create(&session, &nx_crypto_tls_ciphers, session_metadata, sizeof(session_metadata));
    if (status)
    {
        printf("  session create 0x%x\nERROR!\n", status);
        test_control_return(1);
        return;
    }

    for (i = 0; i < LEG_COUNT; i++)
    {
        if (!run_leg(i))
        {
            failures++;
        }
    }

    if (failures)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_process_record_fragment_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    printf("NetX Secure Test:   TLS Process Record Fragment Test...................N/A\n");
    test_control_return(3);
}
#endif
